dependencies:
# Django
# ------------------------------------------------------------------------------
  - pip:
    - Werkzeug==2.0.0 #old value=1.0.1
    - ipdb==0.13.7 #old value = 0.13.4
    - prompt-toolkit==3.0.18 #old value = 3.0.8
    - django-debug-toolbar-request-history==0.1.3  # allows to track ajax requests
    - django-debug-toolbar==3.2.1 #old value=3.1.1
    - django-extensions==3.1.3 #old value=3.0.9
